### ISSUE TITLE
Manuscript

### ISSUE THREAD

**Issue by tpoisot** [BIO6032/2019_replication_LipstichEtAl_1996#12]
Hi guys,

Can you add the manuscript to this repo?

Thanks

**Comment by kiristern** [comment]
[Virulence Project.pdf](https://github.com/BIO6032/2019_replication_LipstichEtAl_1996/files/3233694/Virulence.Project.pdf)

**Comment by sandrinesoeharjono** [comment]
my bad, i removed it before seeing this issue. it's now been placed back in #17 under the name `Manuscript_v1.pdf`
